### ISSUE TITLE
Crashing in GTNH 2.7.0

### ISSUE THREAD

**Issue by SKProCH** [RecursivePineapple/MatterManipulator#2]
While trying to drop in and launch GTNH 2.7.0 i get crash:
```
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: Class gregtech.api.GregTechAPI does not have member field 'java.util.List sThirdPartyMultiRegistration'
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:480)
    at net.minecraft.client.Minecraft.run(Minecraft.java:6099)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

Here is the full log: https://mclo.gs/gsprEjD

**Comment by ABKQPO** [comment]
you need use gregtech-5.09.50.103-2.7.0-mm-11

**Comment by SKProCH** [comment]
Oh, I've carefully reread readme and this noted there, thanks!
