### ISSUE TITLE
Crash after clicking Edit Transform

### ISSUE THREAD

**Issue by ABKQPO** [RecursivePineapple/MatterManipulator#5]
Sometimes problems may arise

```
Time: 2024-12-16 20:02:36 CST
Description: Ticking screen

java.lang.NullPointerException
    at com.recursive_pineapple.matter_manipulator.common.items.manipulator.ItemMatterManipulator.lambda$makeCoordinateEditor$69(ItemMatterManipulator.java:1667)
    at com.recursive_pineapple.matter_manipulator.common.items.manipulator.ItemMatterManipulator.lambda$makeCoordinateEditor$75(ItemMatterManipulator.java:1821)
    at com.gtnewhorizons.modularui.api.screen.ModularWindow.lambda$update$6(ModularWindow.java:198)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.lambda$forEachByLayer$2(IWidgetParent.java:119)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:84)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:71)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:67)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:118)
    at com.gtnewhorizons.modularui.api.screen.ModularWindow.update(ModularWindow.java:194)
    at com.gtnewhorizons.modularui.common.internal.wrapper.ModularGui.func_73876_c(ModularGui.java:446)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
Details:
    Screen name: com.recursive_pineapple.matter_manipulator.common.items.manipulator.ItemMatterManipulator.TransparentModularGui
-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Huan_F'/945, l='MpServer', x=-15.68, y=30.82, z=-15.64]]
    Chunk stats: MultiplayerChunkCache: 4225, 4225
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,4,8), Chunk: (at 8,0,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 263377 game time, 273 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['Huan_F'/945, l='MpServer', x=-15.68, y=30.82, z=-15.64]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6113)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by RecursivePineapple** [comment]
Fixed by https://github.com/RecursivePineapple/MatterManipulator/commit/9af1770eae6735751e05f6ad0d1469bcb2965d8b in v0.0.7
